#!/usr/bin/python

"""
A minimal front end to the Docutils Publisher, producing a manpage.
"""

try:
    import locale
    locale.setlocale(locale.LC_ALL, '')
except:
    pass

from docutils.core import publish_cmdline, default_description


description = ('Generates a manpage from standalone reStructuredText '
               'sources.  ' + default_description)

publish_cmdline(writer_name='manpage', description=description)

